### ISSUE TITLE
Error when using makemessages with --all option

### ISSUE THREAD

**Issue by skolsuper** [ecometrica/django-vinaigrette#11]
If the user calls makemessages with the --all option set, the _get_po_paths function tries to iterate over a None object:

```
if options.get('all'):
    po_paths = _get_po_paths()
```

```
def _get_po_paths(locales=None):
    ...
    for locale in locales:
```

I've made a patch, but I don't know where the regular makemessages function keeps its list of locales or if it just reads it from the directory structure, so my solution is a bit hacky. I will submit a pull request anyway and you can advise me where it's wrong.

**Comment by pauricthelodger** [comment]
It looks like this was fixed in 442f36c0 so I'm going to close this. Thanks for the issue and PR, sorry we didn't get back sooner!
