### ISSUE TITLE
Error when running makemessages in Django 1.7

### ISSUE THREAD

**Issue by aarande** [ecometrica/django-vinaigrette#18]
When running the makemessages command in Django 1.7 I received this error...

django.core.exceptions.ImproperlyConfigured: Command Command defines both "requires_model_validation" and "requires_system_checks", which is illegal. Use only "requires_system_checks".

Once I changed line 48 from requires_model_validation = True to requires_system_checks = True in the makemessage.py command it worked. This seems to be a Django 1.7 issue that these cannot but used at the same time.

**Comment by pauricthelodger** [comment]
Hey @aarande, this is a fairly old case so I'm going to close it. If it's something you come across again, we'll hopefully check it quicker next time =/
