### ISSUE TITLE
issue when running makemessages on Django 1.8

### ISSUE THREAD

**Issue by FooBarQuaxx** [ecometrica/django-vinaigrette#19]
This issues is causes by the change in the arguments definition in Django 1.8. As a quick fix we can add a condition to check Django version if it's lower than 1.8 we apply the old logic otherwise we use the new logic which is basically defining add_arguments  method on the command class.

**Comment by pauricthelodger** [comment]
Hey @FooBarQuaxx, thanks for making the issue and the PR, sorry we didn't get back to you about them. Closing now as the time has passed on this one.
