### ISSUE TITLE
Issue when running makemessages on django 1.10

### ISSUE THREAD

**Issue by incognito2me** [ecometrica/django-vinaigrette#26]
Is support for Django 1.10 going to be released for this project? When running makemessages, our en file is losing all its previous data and other files are occasionally creating rogue extra newlines that make the .po files unable to compile.

**Comment by kousu** [comment]
Well I'm glad you solved it, but to answer the question we are planning to migrate to Django 1.10 ourselves soon, so we'll certainly make sure vinaigrette works there.
