### ISSUE TITLE
Update installation docs to use AppConfig

### ISSUE THREAD

**Issue by Geekfish** [ecometrica/django-vinaigrette#34]
Hello!

In the more recent versions of Django (I think 1.7+) it is generally recommended to put any sort of initialisation logic, such as signal registration, into [AppConfig.ready()](https://docs.djangoproject.com/en/2.1/ref/applications/#django.apps.AppConfig.ready).

Since `vinaigrette.register()` also registers signals, I think it would be well suited to move registration there.

This could be done like:
```python
class MyAppConfig(AppConfig):
    def ready(self):
        vinaigrette.register(self.get_model('Pizza'), ['name', 'description'])
        vinaigrette.register(self.get_model('Ingredient'), ['name', 'origin'])    
```

I would be happy to contribute the patch if you think this is a good idea.

**Comment by jordiecometrica** [comment]
Sure, looking forward to your patch.

**Comment by Geekfish** [comment]
I guess this can be closed!
