### ISSUE TITLE
vinaigrette is TOO GOOD

### ISSUE THREAD

**Issue by CapnKernel** [ecometrica/django-vinaigrette#8]
Hi guys,

Couldn't see a way to contact you directly.  I needed to localise state names I was keeping in a model.  Just want to say that I found vinaigrette, and installing it, reading the docs, and making the code changes gave me change from five minutes!  Amazing!

Thank you very much for making my i18n/l10n day.

**Comment by jordiecometrica** [comment]
More than three years later, I hope it's still good.
